### ISSUE TITLE
Schematics missing

### ISSUE THREAD

**Issue by ProstetnikVogonJeltz** [OpenGammaProject/MicroFC-SiPM-Array-Board#5]
Hi Matthias,

tried to get the Gerbers of V 2.1 processed at JLCPCB, but they complained, that the VIAs are too small (need 0,5/0,25mm) and they 
would have to add Kelvin-Tests (that would add 33€ to a 2€ PCB).
So I decided, to use the PCB-Data provided at Kitspace, but unfortunately it is Rev. 1.0.
Is it possible, to get the Schematics/PCB files for EasyEDA?

Best regards
Uli

**Comment by NuclearPhoenixx** [comment]
Hi there Uli,

looks like I messed up. Accidentally, there were 2 vias with 0.25mm drill hole size, all the others are >0.3mm large. I fixed that for you in the latest Gerber file.

Cheers!

**Comment by ProstetnikVogonJeltz** [comment]
Hallo Matthias,super, vielen lieben Dank dafür 😉!Schöne GrüßeUliAm 01.03.2024 um 12:04 schrieb Matthias ***@***.***>:﻿
Closed #5 as completed.
